#!/usr/bin/env bash

TMP=/tmp/i3lock.png
# SCREENSHOT="scrot -z $PICTURE"

PICTURE='/home/tyrael/Pictures/wallpapers/desktop_view.png'

# BLUR="2x2"
magick $PICTURE          \
       -resize 1920x1080 \
       $TMP 
i3lock -i $TMP
rm $TMP

# $SCREENSHOT
# convert $PICTURE -blur $BLUR $PICTURE
# i3lock -i $PICTURE
# rm $PICTURE
